### ISSUE TITLE
Shouldn't StoreSubscriber be more "reactive"? 

### ISSUE THREAD

**Issue by pzmudzinski** [ReMVVM/ReMVVM#1]
I really like your article but have major question about the way ViewModels subscribe to store. 
In your example it's done via this method:
```
    func didChange(state: AppState, oldState: AppState) {
        if oldState.user != nil && state.user == nil {
            // reset values on logout
            firstName.onNext("")
            lastName.onNext("")
        }
    }
```

Even in such trivial example it brings notion of state (`state.user` was something and now it's `nil`), where whole Reactive programming is about avoiding managing state as it brings a lot of complexity with new properties (e.g. there might a state when user `isLoggingIn`). 
I imagine that it would make more sense if ViewModel would get an `Observable<AppState>` and would map state to its output, like:
`ViewModel = function(state) -> Output`.

In React framework it's called `mapStateToProps` which takes whatever `View` needs from state and maps it to representable structure.

So for example if you want to display current logged in user it would like that:
```
class UserNameViewModel {
   // output for a view
   let userName: Observable<String> 
 
   init(appState: Observable<AppState>) {
       userName = appState.map { state.user?.username ?? "You are not logged in." }
   }
}
```

**Comment by dgrzeszczak** [comment]
Hey, thank you for the feedback. It's very interesting and I really like it. The main idea behind the ReMVVM is to not have any dependency to Reactive framework so that's why there is nothing like that by default.

The biggest feature of current implementation for ViewModels  which implement StoreSubscriber protocol is automatic subsciption to the store (you don't need to subscribe ViewModels manually to the store).

Looking on your example I created RxStore which is simple wraper of the Store and provides Observable<State>. 

```
class RxStore<State: StoreState>  {

    let state: Observable<State>

    init(with store: Store<State>) {
        state = Observable<State>.create { observer -> Disposable in
            let rxObserver = StateSubscriber(observer: observer)
            store.add(subscriber: rxObserver)

            return Disposables.create {
                store.remove(subscriber: rxObserver)
            }
        }
        .share(replay: 1)
        .startWith(store.state)
    }

    private class StateSubscriber<Element>: StoreSubscriber {
        let observer: AnyObserver<Element>
        init(observer: AnyObserver<Element>) {
            self.observer = observer
        }

        func didChange(state: Element, oldState: Element) {
            observer.onNext(state)
        }
    }
}
```

LoginViewModel may look like: 

```
struct LoginViewModel {

    let firstName = BehaviorSubject(value: "")
    let lastName = BehaviorSubject(value: "")

    private let disposeBag = DisposeBag()
    init(state: Observable<AppState>) {
        state.map { $0.user?.firstName ?? "" }.bind(to: firstName).disposed(by: disposeBag)
        state.map { $0.user?.lastName ?? "" }.bind(to: lastName).disposed(by: disposeBag)
    }
}
```

Then you have to add factory for the LoginViewModel cause it's not longer Initializable

```
      factory.add { LoginViewModel(state: rxStore.state) }
```

You can see full example on branch feature/rxStore. 

I think the next step would be to add automatic dependency injection of Observable<State> to 'all' view models (StoreSubscribers ?) but it seems it will require some changes in ReMVVM. That's seems to be the goal for 1.0.1 version of ReMVVM. Please let me know what do you think and feel free to contribute :)
